name: xxs_gen

# training
steps: 25000
batch_size: 64
learning_rate: 0.003
accumulate_grad_batches: 1

# architecture 
embed_dim: 16
num_heads: 2
num_layers: 8
num_pixels: 28
num_vocab: 16

classify: False

gpus: 1
precision: 16

